version: '2'

services:
  court-ca:
    container_name: court-ca
    extends:
      file: ./ca-base.yaml
      service: ca-base
    image: court-ca
    ports:
      - 7054:7054

  prison-ca:
    container_name: prison-ca
    extends:
      file: ./ca-base.yaml
      service: ca-base
    image: prison-ca
    ports:
      - 8054:7054

  investigation-ca:
    container_name: investigation-ca
    extends:
      file: ./ca-base.yaml
      service: ca-base
    image: investigation-ca
    ports:
      - 9054:7054

  law-enforcement-ca:
    container_name: law-enforcement-ca
    extends:
      file: ./ca-base.yaml
      service: ca-base
    image: law-enforcement-ca
    ports:
      - 10054:7054

  orderer0:
    container_name: orderer0
    image: orderer
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/orderer/crypto/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/orderer/crypto/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/orderer/crypto/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/orderer/crypto/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/orderer/crypto/tls/ca.crt]
    working_dir: /orderer
    command: orderer
    ports:
      - 7050:7050

  court-peer:
    container_name: court-peer
    extends:
      file: ./peer-base.yaml
      service: peer-base
    image: court-peer
    environment:
      - CORE_PEER_ID=court-peer
      - CORE_PEER_ADDRESS=court-peer:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=court-peer:7051
      - CORE_PEER_LOCALMSPID=CourtOrgMSP
    ports:
      - 7051:7051
      - 7053:7053
    depends_on:
      - orderer0

  prison-peer:
    container_name: prison-peer
    extends:
      file: ./peer-base.yaml
      service: peer-base
    image: prison-peer
    environment:
      - CORE_PEER_ID=prison-peer
      - CORE_PEER_ADDRESS=prison-peer:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=prison-peer:7051
      - CORE_PEER_LOCALMSPID=PrisonOrgMSP
    ports:
      - 8051:7051
      - 8053:7053
    depends_on:
      - orderer0
      - court-peer

  investigation-peer:
    container_name: investigation-peer
    extends:
      file: ./peer-base.yaml
      service: peer-base
    image: investigation-peer
    environment:
      - CORE_PEER_ID=investigation-peer
      - CORE_PEER_ADDRESS=investigation-peer:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=investigation-peer:7051
      - CORE_PEER_LOCALMSPID=InvestigationOrgMSP
    ports:
      - 9051:7051
      - 9053:7053
    depends_on:
      - orderer0
      - court-peer
      - prison-peer

  law-enforcement-peer:
    container_name: law-enforcement-peer
    extends:
      file: ./peer-base.yaml
      service: peer-base
    image: law-enforcement-peer
    environment:
      - CORE_PEER_ID=law-enforcement-peer
      - CORE_PEER_ADDRESS=law-enforcement-peer:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=law-enforcement-peer:7051
      - CORE_PEER_LOCALMSPID=LawEnforcementOrgMSP
    ports:
      - 10051:7051
      - 10053:7053
    depends_on:
      - orderer0
      - court-peer
      - prison-peer
      - investigation-peer

  web:
    container_name: web
    image: web
    environment:
      - PORT=8000
      - DOCKER_SOCKET_PATH=/host/var/run/docker.sock
      - DOCKER_CCENV_IMAGE=hyperledger/fabric-ccenv:latest
    ports:
      - 8000:8000
    volumes:
      - /var/run/:/host/var/run/
    depends_on:
      - orderer0
      - court-ca
      - court-peer
      - prison-ca
      - prison-peer
      - investigation-ca
      - investigation-peer
      - law-enforcement-ca
      - law-enforcement-peer
